dataset:
    ensamble:
        flag: false
        train_virtual: ""
        train_real: ""
        valid_real: ""
        split: ""
    root_train: "data"
    root_valid: ""
    root_test: "test_imgs"

    train:
        virtual: "train_dataset.txt"
        real: ""

    test: "test_set.txt"
    
    validation:
        valid: ""
        percentage_val      : 0.8

model:
    device               : "cuda"    # cpu or cuda
    backbone             : "resnet50" 
    pretrained           : true
    pretrained_backbone  : false
    num_class            : 2

train:
    log_file            : "trainlogs/virtual_train_log.txt"
    batch_size          : 3
    num_workers         : 8
    epochs              : 10
    sampler             : true
    path_saved_model    : "models/checkpoint_train_virtual.pth"
    checkpoint          : ""      # checkpoint to resume, useful for starting from an interrupted training
    pretrained_model    : ""      # pre-trained model to resume
    lr                  : 0.005
    momentum            : 0.9
    weight_decay        : 0.0005
    lr_scheduler        :
        flag                : false
        lr_gamma            : 0.1
        lr_step_size        : 3
    mixed_batch         : false
